# -------------------------------------------------


# PARÁMETROS GLOBALES DEL PROYECTO


# -------------------------------------------------


base:


  random_state: 1


  target_col: 'credit_risk'





# -------------------------------------------------


# 1. RUTAS DE DATOS


# -------------------------------------------------


data:


  raw: "../data/raw/german_credit_modified.csv"


  processed: "data/processed/02_df_data_preparation_01.csv"



  train: "../data/processed/02_df_data_train_01.csv"



  test: "../data/processed/02_df_data_test_01.csv"




# -------------------------------------------------


# 2. PARÁMETROS DE LIMPIEZA DE DATOS


# (Usado por el script en src/preprocessing/clean_data.py)


# -------------------------------------------------


data_cleaning:


  rename_cols:


    - 'status'


    - 'duration'


    - 'credit_history'


    - 'purpose'


    - 'amount'


    - 'savings'


    - 'employment_duration'


    - 'installment_rate'


    - 'personal_status_sex'


    - 'other_debtors'


    - 'present_residence'


    - 'property'


    - 'age'


    - 'other_installment_plans'


    - 'housing'


    - 'number_credits'


    - 'job'


    - 'people_liable'


    - 'telephone'


    - 'foreign_worker'


    - 'credit_risk'


    - 'mixed'


  drop_cols:


    - 'mixed'


  outlier_cols:


    duration: 60


    age: 65


    amount: 12500


  rare_cols:


    purpose: 0.04


    other_debtors: 0.04


    other_installment_plans: 0.04


  test_size: 0.2


  random_state: 1





# -------------------------------------------------


# 3. PARÁMETROS DE PREPROCESAMIENTO DE FEATURES


# (Usado por el script en src/training/train_model.py)


# -------------------------------------------------


preprocessing:


  numeric:


    features: ['duration', 'amount', 'age']


    imputer_strategy: 'mean'


  nominal:


    features: ['status', 'credit_history', 'purpose', 'savings', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker']


    imputer_strategy: 'most_frequent'


  ordinal:


    features: ['employment_duration', 'installment_rate', 'present_residence', 'number_credits', 'people_liable']


    imputer_strategy: 'most_frequent'





# -------------------------------------------------


# 4. CONFIGURACIÓN DEL GRID SEARCH (NUEVA SECCIÓN)


# -------------------------------------------------


grid_search:


  cv: 5 # Pliegues (folds) para la validación cruzada


  n_repeats: 3 # Repeticiones para RepeatedStratifiedKFold


  n_jobs: -1 # Usar todos los procesadores


  scoring: 'roc_auc' # Métrica principal a optimizar


  verbose: 1





# -------------------------------------------------


# 5. CONFIGURACIÓN DE ENTRENAMIENTO (EXPERIMENTOS)


# (Modificado para GridSearch)


# -------------------------------------------------


training:

  # ------------------------------------------------------------
  # LOGISTIC REGRESSION (3 variantes)
  # ------------------------------------------------------------
  logistic_regression_v1:
    name: "LogisticRegression"
    resampler: "SMOTE"
    param_grid:
      model__C: [0.01, 0.1]
      model__solver: ['liblinear']
      model__penalty: ['l1']
      model__class_weight: ['balanced']
      model__random_state: [1]



  # ------------------------------------------------------------
  # RANDOM FOREST (3 variantes)
  # ------------------------------------------------------------
  random_forest_v1:
    name: "RandomForest"
    resampler: "NearMiss"
    resampler_params:
      version: 3
    param_grid:
      model__n_estimators: [100, 200]
      model__max_depth: [5, 10, 15]
      model__min_samples_split: [2,3,4]
      model__class_weight: ["balanced"]


  # ------------------------------------------------------------
  # XGBOOST (3 variantes)
  # ------------------------------------------------------------
  xgboost_v1:
    name: "XGBoost"
    resampler: "NearMiss"
    param_grid:
      model__n_estimators: [100, 200]
      model__max_depth: [3]
      model__learning_rate: [0.1]
      model__subsample: [0.8]
      model__colsample_bytree: [0.8]





# -------------------------------------------------


# 6. PARÁMETROS DE GUARDADO DE MODELOS (MFLOW)


# -------------------------------------------------


mlflow:

  mode: "cloud"


  experiment_name: "Experimento-Conexión-MLFlow-Grupo57"


  evaluation_experiment_name: "MLFlow-Grupo57-Evaluación"


  tracking_uri: "https://mlflow-super-g57-137680020436.us-central1.run.app"





# -------------------------------------------------


# 7. PARÁMETROS DE GUARDADO DE REPORTES


# -------------------------------------------------


reports:


  dir: 'reports' # Directorio para guardar plots y reportes HTML
