# -------------------------------------------------
# PARÁMETROS GLOBALES DEL PROYECTO
# -------------------------------------------------
base:
  random_state: 1
  target_col: 'credit_risk'

# -------------------------------------------------
# 1. RUTAS DE DATOS
# -------------------------------------------------
data:
  raw: "data/raw/german_credit_modified.csv"
  processed: "data/processed/02_df_data_preparation_01.csv"
  train: 'data/processed/02_df_data_train_01.csv'
  test: 'data/processed/02_df_data_test_01.csv'

# -------------------------------------------------
# 2. PARÁMETROS DE LIMPIEZA DE DATOS
# (Usado por el script en src/preprocessing/clean_data.py)
# -------------------------------------------------
data_cleaning:
  rename_cols:
    - 'status'
    - 'duration'
    - 'credit_history'
    - 'purpose'
    - 'amount'
    - 'savings'
    - 'employment_duration'
    - 'installment_rate'
    - 'personal_status_sex'
    - 'other_debtors'
    - 'present_residence'
    - 'property'
    - 'age'
    - 'other_installment_plans'
    - 'housing'
    - 'number_credits'
    - 'job'
    - 'people_liable'
    - 'telephone'
    - 'foreign_worker'
    - 'credit_risk'
    - 'mixed'
  drop_cols:
    - 'mixed'
  outlier_cols:
    duration: 60
    age: 65
    amount: 12500
  rare_cols:
    purpose: 0.04
    other_debtors: 0.04
    other_installment_plans: 0.04
  test_size: 0.2
  random_state: 1

# -------------------------------------------------
# 3. PARÁMETROS DE PREPROCESAMIENTO DE FEATURES
# (Usado por el script en src/training/train_model.py)
# -------------------------------------------------
preprocessing:
  numeric:
    features: ['duration', 'amount', 'age']
    imputer_strategy: 'mean'
  nominal:
    features: ['status', 'credit_history', 'purpose', 'savings', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker']
    imputer_strategy: 'most_frequent'
  ordinal:
    features: ['employment_duration', 'installment_rate', 'present_residence', 'number_credits', 'people_liable']
    imputer_strategy: 'most_frequent'

# -------------------------------------------------
# 4. CONFIGURACIÓN DEL GRID SEARCH (NUEVA SECCIÓN)
# -------------------------------------------------
grid_search:
  cv: 5 # Pliegues (folds) para la validación cruzada
  n_repeats: 3 # Repeticiones para RepeatedStratifiedKFold
  n_jobs: -1 # Usar todos los procesadores
  scoring: 'roc_auc' # Métrica principal a optimizar
  verbose: 1

# -------------------------------------------------
# 5. CONFIGURACIÓN DE ENTRENAMIENTO (EXPERIMENTOS)
# (Modificado para GridSearch)
# -------------------------------------------------
training:
  
  logistic_regression:
    name: "LogisticRegression"
    resampler: "SMOTE"
    resampler_params:
      random_state: 1
    # CAMBIADO: 'model_params' -> 'param_grid' con prefijo 'model__'
    param_grid:
      model__C: [0.01, 0.1, 1, 10]
      model__penalty: ['l1', 'l2']
      model__solver: ['liblinear'] # 'l1' solo funciona con 'liblinear'
      model__class_weight: ['balanced']
      model__random_state: [1]

  random_forest:
    name: "RandomForest"
    resampler: "NearMiss"
    resampler_params:
      version: 3
    # CAMBIADO: 'model_params' -> 'param_grid' con prefijo 'model__'
    param_grid:
      model__n_estimators: [100, 200, 300]
      model__max_depth: [5, 10, 15]
      model__min_samples_leaf: [2, 4]
      model__min_samples_split: [2, 5]
      model__class_weight: ["balanced"]
      model__bootstrap: [False]
      model__random_state: [1]

  xgboost:
    name: "XGBoost"
    resampler: "NearMiss"
    resampler_params:
      version: 3
    # CAMBIADO: 'model_params' -> 'param_grid' con prefijo 'model__'
    param_grid:
      model__n_estimators: [100, 200]
      model__max_depth: [2, 4, 6]
      model__learning_rate: [0.01, 0.1]
      model__subsample: [0.4, 0.6]
      model__colsample_bytree: [0.5, 0.7]
      model__reg_alpha: [1.0, 2.0]
      model__reg_lambda: [4.0, 5.0]
      model__objective: ['binary:logistic']
      model__tree_method: ['hist']
      model__random_state: [1]
      model__n_jobs: [-1]

  mlp:
    name: "MLP"
    resampler: "SMOTETomek"
    resampler_params:
      random_state: 1
    # CAMBIADO: 'model_params' -> 'param_grid' con prefijo 'model__'
    param_grid:
      model__hidden_layer_sizes: [[8, 4], [10, 5]] # Lista de listas
      model__activation: ['relu', 'tanh']
      model__solver: ['adam']
      model__max_iter: [1500]
      model__alpha: [1, 5]
      model__learning_rate: ['adaptive']
      model__learning_rate_init: [0.007, 0.01]
      model__tol: [0.0001]
      model__early_stopping: [True]
      model__n_iter_no_change: [15]
      model__random_state: [1]

  svc:
    name: "SVC"
    resampler: "SMOTETomek"
    resampler_params:
      random_state: 1
    # CAMBIADO: 'model_params' -> 'param_grid' con prefijo 'model__'
    param_grid:
      model__C: [0.1, 1, 10]
      model__kernel: ['rbf', 'linear'] # 'linear' puede ser lento
      model__gamma: ['scale', 'auto']
      model__probability: [True] # Necesario para ROC AUC
      model__class_weight: ['balanced']
      model__random_state: [1]

# -------------------------------------------------
# 6. PARÁMETROS DE GUARDADO DE MODELOS (MFLOW)
# -------------------------------------------------
mlflow:
  experiment_name: "Experimento-Conexión-MLFlow-Grupo57"
  evaluation_experiment_name: "MLFlow-Grupo57-Evaluación"
  tracking_uri: "https://mlflow-super-g57-137680020436.us-central1.run.app"

# -------------------------------------------------
# 7. PARÁMETROS DE GUARDADO DE REPORTES
# -------------------------------------------------
reports:
  dir: 'reports' # Directorio para guardar plots y reportes HTML